package entity;
// Generated Oct 22, 2016 3:47:30 PM by Hibernate Tools 4.3.1



/**
 * AdminLogin generated by hbm2java
 */
public class AdminLogin  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;

    public AdminLogin() {
    }

    public AdminLogin(String name, String password) {
       this.name = name;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


