package entity;
// Generated Oct 22, 2016 3:47:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String gender;
     private String address;
     private String district;
     private String country;
     private String phone;
     private String email;
     private Date dateofBirth;
     private double salary;

    public Employee() {
    }

    public Employee(String fname, String lname, String gender, String address, String district, String country, String phone, String email, Date dateofBirth, double salary) {
       this.fname = fname;
       this.lname = lname;
       this.gender = gender;
       this.address = address;
       this.district = district;
       this.country = country;
       this.phone = phone;
       this.email = email;
       this.dateofBirth = dateofBirth;
       this.salary = salary;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateofBirth() {
        return this.dateofBirth;
    }
    
    public void setDateofBirth(Date dateofBirth) {
        this.dateofBirth = dateofBirth;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }




}


