package entity;
// Generated Oct 22, 2016 3:47:30 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private String proName;
     private String proDetails;
     private int qty;
     private double price;

    public Product() {
    }

    public Product(String proName, String proDetails, int qty, double price) {
       this.proName = proName;
       this.proDetails = proDetails;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getProDetails() {
        return this.proDetails;
    }
    
    public void setProDetails(String proDetails) {
        this.proDetails = proDetails;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


